version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: frontend
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.0
    - 12.8.3
    - 13.0.0
    - 13.0.10
    - 13.0.13
    - 13.1.1
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: backend
